;; -*- mode: eask; lexical-binding: t -*-

(package "on"
         "0.1.0"
         "Hooks for faster startup")

(website-url "https://github.com/elp-revive/on.el")
(keywords "convenience")

(package-file "on.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "27.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
